default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: vacation_tracker_development
  username: vacation_tracker_user
  password:

test: &test
  <<: *default
  database: vacation_tracker_test
  username: vacation_tracker_user
  password:

cucumber:
  <<: *test