# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 746d53e5241fbc35d49e209812709636b37d838465544c8999b16308fedf5f37bd1786a416bd5ab64857f9402da488a7e41d5769912fd283a40a5e8d95a97da5

test:
  secret_key_base: 78d1c735269b48b813fd34f9c300ee25c0e2f45b291fa3f43ecf4479755ac72c6dab78f4122e7d59934f3b5fe346b3f32d4576cc304cb874fecdfca89d39fedd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
